name: Build, test and push container image
on:
  workflow_call:
    inputs:
      continue-on-error:
        type: string
      build_args:
        type: string
      dockerfile:
        type: string
      tag:
        type: string

env:
  test-tag: ghcr.io/kokkos/ci-containers/${{ inputs.dockerfile }}:${{ inputs.tag }}-${{github.sha}}

jobs:
  build-test-push:
    continue-on-error: ${{ inputs.continue-on-error == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        if: github.repository_owner == 'kokkos' && ( github.event_name == 'push' ||  github.event_name == 'schedule' )
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert build_args
        id: build_args
        run: |
          echo "args<<EOF" >> $GITHUB_OUTPUT
          echo ${{ inputs.build_args }} | sed 's/,/\n/' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Build new image and Load it into Docker for testing
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.test-tag }}
          file: ${{ inputs.dockerfile }}
          build-args: ${{ steps.build_args.outputs.args }}
          load: true
      - name: Checkout kokkos
        uses: actions/checkout@v3
        with:
          repository: kokkos/kokkos
          path: kokkos
      - name: Build and Test Kokkos using updated image
        run: |
          docker run -t --rm -v ${{ github.workspace }}/kokkos:/kokkos -w /kokkos ${{ env.test-tag }} \
            sh -c \
              "cmake -B builddir \
                -DKokkos_ENABLE_HWLOC=ON \
                -DKokkos_ENABLE_BENCHMARKS=ON \
                -DKokkos_ENABLE_EXAMPLES=ON \
                -DKokkos_ENABLE_TESTS=ON && \
              cmake --build builddir --parallel 2 && \
              ctest --test-dir builddir --output-on-failure"
      - name: Push the image into Github Container Registry
        uses: docker/build-push-action@v4
        if: ${{ github.repository_owner == 'kokkos' && ( github.event_name == 'push' ||  github.event_name == 'schedule' ) }}
        with:
          tags: ghcr.io/kokkos/ci-containers/${{ inputs.dockerfile }}:${{ inputs.tag }}
          pull: true
          push: true
