name: Continuous integration reusable workflow
on:
  workflow_call:
    inputs:
      continue-on-error:
        required: true
        type: string
      build_args:
        type: string
      dockerfile:
        type: string
      tag:
        type: string

jobs:
  build-and-push-candidate:
    continue-on-error: ${{ inputs.continue-on-error == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        if: github.repository_owner == 'kokkos' && ( github.event_name == 'push' ||  github.event_name == 'schedule' )
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert build_args
        id: build_args
        run: |
          echo "args<<EOF" >> $GITHUB_OUTPUT
          echo ${{ inputs.build_args }} | sed 's/,/\n/' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Build and Push Docker images for Github Container Registry
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/kokkos/ci-containers/${{ inputs.dockerfile }}:${{ inputs.tag }}-${{github.sha}}
          file: ${{ inputs.dockerfile }}
          build-args: ${{ steps.build_args.outputs.args }}
          pull: true
          push: ${{ github.repository_owner == 'kokkos' && ( github.event_name == 'push' ||  github.event_name == 'schedule' ) }}

  test-kokkos:
    needs: build-and-push-candidate
    uses: ./.github/workflows/test-kokkos.yml
    with:
      dockerfile: ${{ inputs.dockerfile }}
      tag: ${{ inputs.tag }}

  push-stable:
    needs: [build-and-push-candidate, test-kokkos]
    runs-on: ubuntu-latest
    steps:
      - name: Push the image with a "stable" tag
        run: |
          echo "Find a way to push the previously built image with a different tag, re-run `Build and push` if no better option is available"
