name: CI
on:
  push:
    branches:
      - main
      - test-kokkos
  pull_request:
    branches:
      - main

jobs:
  CI:
    strategy:
        matrix:
          config:
            - {dockerfile: 'fedora',   tag: 'latest'}
            - {dockerfile: 'fedora',   tag: 'rawhide',  build_args: 'TAG=rawhide',  continue-on-error: 'true'}
            - {dockerfile: 'ubuntu',   tag: 'latest'}
            - {dockerfile: 'ubuntu',   tag: 'rolling',  build_args: 'TAG=rolling'}
            - {dockerfile: 'ubuntu',   tag: 'devel',    build_args: 'TAG=devel',    continue-on-error: 'true'}
            - {dockerfile: 'opensuse', tag: 'latest'}
            - {dockerfile: 'fedora',   tag: 'intel',    build_args: 'INTEL=yes',    continue-on-error: 'true'}
    uses: ./.github/workflows/build-and-push.yml
    with:
      continue-on-error: ${{ matrix.config.continue-on-error }}
      build_args: ${{ matrix.config.build_args }}
      dockerfile: ${{ matrix.config.dockerfile }}
      tag: ${{ matrix.config.tag }}
